# theme: jekyll-theme-minimal


title: Marc Harrison
email: marc@marcharrison.net
description: >- # this means to ignore newlines until "baseurl:"
  Founder of Listium. Startup adviser. Lifelong learner.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcharrison.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marcharrison
github_username: harro33
reddit_username: harro33
listium_username: Marc
google_analytics: UA-1806586-1

remote_theme: fongandrew/hydeout
# plugins:
#   - jekyll-feed

gems:
- jekyll-email-protect
